LIBS = AlignedSeq.pm \
       Bed.pm \
       Cigar.pm \
       Fasta.pm \
       MacsXls.pm \
       Position.pm \
       SeqName.pm \
       Sequence.pm \
       Swembl.pm

all:

install:
	cp $(LIBS) $(LIBDIR)

clean:
