#!/usr/bin/perl

use strict;
use Bio::EnsEMBL::Registry;
use Data::Dumper;

###############################################################################
###############################################################################

my $registry = 'Bio::EnsEMBL::Registry';
$registry->load_registry_from_db(-host=>"ensembldb.ensembl.org",
                                 -user=>"anonymous");
my $adaptors = $registry->get_all_adaptors(-SPECIES=>"homo sapiens",-GROUP=>"core");
foreach my $adap (@$adaptors) {
  print Dumper($adap);
}
