SCRIPTS = cloneFile \
          countSyntenicRegions \
          findFullLoci \
          getGenomeSyntenyMap \
          makeVennDiagramForTrnaLoci \
          mapSyntenicRegions \
          summarizeEnsemblAnnotations

BINDIR = ~/bin

all:

install:
	cp $(SCRIPTS) $(BINDIR)

clean:
